### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by mikolajmr** [krentzd/napari-clemreg#15]
_I was trying to install clem-reg into its own conda environment, but during the pip install for clemreg I get the following error:_
----------------------------
Requirement already satisfied: pure-eval in /opt/miniconda3/lib/python3.9/site-packages (from stack-data->IPython>=7.7.0->napari-console>=0.0.6->napari->napari-clemreg) (0.2.2)
Building wheels for collected packages: probreg
  Building wheel for probreg (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/miniconda3/bin/python /opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/tmpdywq_4df
       cwd: /private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-install-f7lb53e3/probreg_570cf8d1147f40c0868bc3e2b73645ed
  Complete output (88 lines):
  Found Eigen version 3.4.0 in: third_party/eigen
  Found Eigen version 3.4.0 in: third_party/eigen
  Found Eigen version 3.4.0 in: third_party/eigen
  Found Eigen version 3.4.0 in: third_party/eigen
  Found Eigen version 3.4.0 in: third_party/eigen
  Found Eigen version 3.4.0 in: third_party/eigen
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-cpython-39
  creating build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/bcpd.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/transformation.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/cost_functions.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/math_utils.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/version.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/se3_op.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/gmmtree.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/l2dist_regs.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/log.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/filterreg.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/features.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/gaussian_filtering.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/callbacks.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/gauss_transform.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/cpd.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  copying probreg/cupy_utils.py -> build/lib.macosx-10.9-x86_64-cpython-39/probreg
  running build_ext
  creating var
  creating var/folders
  creating var/folders/v8
  creating var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj
  creating var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/miniconda3/include -arch x86_64 -I/opt/miniconda3/include -fPIC -O2 -isystem /opt/miniconda3/include -arch x86_64 -I/opt/miniconda3/include/python3.9 -c /var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/tmpfyzznude.cpp -o var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/tmpfyzznude.o -std=c++14
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/miniconda3/include -arch x86_64 -I/opt/miniconda3/include -fPIC -O2 -isystem /opt/miniconda3/include -arch x86_64 -I/opt/miniconda3/include/python3.9 -c /var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/tmpnrkupczw.cpp -o var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/tmpnrkupczw.o -std=c++11
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  Traceback (most recent call last):
    File "/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 248, in <module>
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/normal/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1244, in run_command
      super().run_command(command)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/private/var/folders/v8/3bbcf68x2_d9w00s9qc15hb9d0dddj/T/pip-build-env-umq2b1n1/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "<string>", line 239, in build_extensions
    File "<string>", line 221, in cpp_flag
  RuntimeError: Unsupported compiler -- at least C++11 support is needed!
  ERROR: Failed building wheel for probreg
Failed to build probreg
ERROR: Could not build wheels for probreg which use PEP 517 and cannot be installed directly
--------------------------------
How do I get it to build a wheel?

**Comment by martlj** [comment]
I think we managed to solve this one by email with Melissa - the solution was to explicitly install a C++ compiler in the conda environment with
`conda install -c conda-forge cxx-compiler`
which should handle getting the correct tools for the OS in use.
